[file:iodef.xml]
source=$ROSE_SUITE_DIR/app/lfric_atm/file/iodef.xml

[!namelist:formulation]
diagnostic_mode_conv=.true.
use_multires_coupling=.true.

[namelist:diagnostic_mode_conv]
conv_mesh_name='multigrid_l2'

[namelist:multires_coupling]
multires_coupling_mesh_tags='dynamics','multigrid_l2'
orography_mesh_name='dynamics'
coarse_rad_aerosol=.false.
lowest_order_aero_flag=.false.